apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: developer	
  name: nlw-setup-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: nlw-setup-web.wagnercastro.ml
    http:
      paths:
      - path: /
        backend:
          serviceName: nlw-setup-web-service
          servicePort: 80


  