apiVersion: v1
kind: Service
metadata:
  namespace: developer
  name: nlw-setup-web-service
spec:
  selector:
    app: nlw-setup-web-api
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
  - protocol: TCP
    name: https
    port: 443
    targetPort: 8080
