# FROM node:18.13.0 as common-build-stage

# RUN groupadd api-group
# RUN useradd -ms /bin/bash api-user
# WORKDIR /app
# RUN chown -R api-user:api-group /app

# USER api-user
# COPY package.json /app/

# RUN npm install

# COPY . /app/

# # RUN npx prisma generate

# EXPOSE 3333
# ENV HOST 0.0.0.0

# # Dvelopment build stage
# FROM common-build-stage as production-build-stage
# CMD ["npm", "run", "dev"]

