version: "3"

services:
  server-production:
    build:
      context: ./
      dockerfile: Dockerfile.2
      # target: production-build-stage
    ports:
      - "3333:3333"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    extra_hosts:
      - "host.docker.internal:host-gateway"
