version: "3"

services:
  production:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production-build-stage
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
    extra_hosts:
      - "host.docker.internal:host-gateway"
