version: "3.5"

services:
  ### NODE ##############################################
  development:
    build:
      context: ./.docker/bin/node
      dockerfile: Dockerfile
      # target: development-build-stage
    entrypoint: sh -c "npm install && npm run dev"
    # command: ["nodemon", "--exec", "npm", "run", "dev"]
    volumes:
      - ./:/var/www
    ports:
      - "3030:3030"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
    extra_hosts:
      - "host.docker.internal:host-gateway"
#
# Resource Container
# $ docker stats id_container
# $ docker stats development
#
